#[derive(Debug, Clone)]
pub enum SlicerPreset {
    PrusaSlicer { version: String },
    SuperSlicer { version: String },
    OrcaSlicer { version: String },
    IdeaMaker { version: String },
    Cura { version: Option<String> },
    Simplify3D { version: String },
}

impl std::fmt::Display for SlicerPreset {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SlicerPreset::PrusaSlicer { version } => write!(f, "PrusaSlicer {}", version),
            SlicerPreset::SuperSlicer { version } => write!(f, "SuperSlicer {}", version),
            SlicerPreset::OrcaSlicer { version } => write!(f, "OrcaSlicer {}", version),
            SlicerPreset::IdeaMaker { version } => write!(f, "ideaMaker {}", version),
            SlicerPreset::Cura { version: None } => write!(f, "Cura"),
            SlicerPreset::Cura {
                version: Some(version),
            } => write!(f, "Cura {}", version),
            SlicerPreset::Simplify3D { version } => write!(f, "Simplify3D {}", version),
        }
    }
}

impl SlicerPreset {
    pub fn determine(comment: &str) -> Option<SlicerPreset> {
        Self::try_slic3r(comment)
            .or_else(|| Self::try_ideamaker(comment))
            .or_else(|| Self::try_cura_old(comment))
            .or_else(|| Self::try_cura_new(comment))
            .or_else(|| Self::try_simplify3d(comment))
    }

    fn try_slic3r(comment: &str) -> Option<SlicerPreset> {
        extract_version_before(comment, "PrusaSlicer", "on")
            .map(|version| SlicerPreset::PrusaSlicer { version })
            .or_else(|| {
                extract_version_before(comment, "SuperSlicer", "on")
                    .map(|version| SlicerPreset::SuperSlicer { version })
            })
            .or_else(|| {
                extract_version_before(comment, "OrcaSlicer", "on")
                    .map(|version| SlicerPreset::OrcaSlicer { version })
            })
    }

    fn try_ideamaker(comment: &str) -> Option<SlicerPreset> {
        extract_after_whitespace(comment, "Sliced by ideaMaker").and_then(|value| {
            value.rfind(',').map(|end| SlicerPreset::IdeaMaker {
                version: value[..end].into(),
            })
        })
    }

    fn try_cura_old(comment: &str) -> Option<SlicerPreset> {
        extract_after_whitespace(comment, "Generated with Cura_SteamEngine").map(|version| {
            SlicerPreset::Cura {
                version: Some(version.into()),
            }
        })
    }

    fn try_cura_new(comment: &str) -> Option<SlicerPreset> {
        comment
            .contains("GENERATOR.NAME:Cura_SteamEngine")
            .then_some(SlicerPreset::Cura { version: None })
    }

    fn try_simplify3d(comment: &str) -> Option<SlicerPreset> {
        extract_after_whitespace(comment, "Simplify3D(R)")
            .and_then(|value| value.strip_prefix("Version"))
            .and_then(strip_leading_whitespace)
            .map(|version| SlicerPreset::Simplify3D {
                version: version.into(),
            })
    }
}

fn extract_after_whitespace<'a>(input: &'a str, marker: &str) -> Option<&'a str> {
    let start = input.find(marker)? + marker.len();
    strip_leading_whitespace(&input[start..])
}

fn strip_leading_whitespace(input: &str) -> Option<&str> {
    let first = input.chars().next()?;
    first.is_whitespace().then(|| &input[first.len_utf8()..])
}

fn extract_version_before(input: &str, marker: &str, suffix: &str) -> Option<String> {
    let value = extract_after_whitespace(input, marker)?;
    value
        .char_indices()
        .rev()
        .find(|(index, character)| {
            character.is_whitespace() && value[index + character.len_utf8()..].starts_with(suffix)
        })
        .map(|(end, _)| value[..end].into())
}

#[cfg(test)]
mod tests {
    use super::SlicerPreset;

    #[test]
    fn recognizes_supported_slicer_markers_without_regular_expressions() {
        let cases = [
            (
                "generated by PrusaSlicer 2.8.1 on 2026-09-03",
                "PrusaSlicer 2.8.1",
            ),
            ("SuperSlicer 2.5.60 on 2026-09-03", "SuperSlicer 2.5.60"),
            ("OrcaSlicer 2.3.1 on 2026-09-03", "OrcaSlicer 2.3.1"),
            ("Sliced by ideaMaker 5.2.3, 2026-09-03", "ideaMaker 5.2.3"),
            ("Generated with Cura_SteamEngine 5.10.0", "Cura 5.10.0"),
            ("GENERATOR.NAME:Cura_SteamEngine", "Cura"),
            ("Simplify3D(R) Version 5.1.2", "Simplify3D 5.1.2"),
        ];

        for (comment, expected) in cases {
            assert_eq!(
                SlicerPreset::determine(comment).unwrap().to_string(),
                expected
            );
        }
    }

    #[test]
    fn rejects_similar_but_incomplete_markers() {
        for comment in [
            "PrusaSlicer 2.8.1",
            "Sliced by ideaMaker5.2.3,",
            "Generated with Cura_SteamEngine",
            "Simplify3D(R) Version5.1.2",
        ] {
            assert!(SlicerPreset::determine(comment).is_none(), "{comment}");
        }
    }
}
